# Generated by Django 6.0.6 on 2026-06-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USDT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='label',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
